product_Management/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;
use App\Http\Controllers\StockController;

/*
Routing cho web
| ------------------------------------------------- -------------------------
| Các tuyến web
| ------------------------------------------------- -------------------------
|
| Đây là nơi bạn có thể đăng ký các tuyến web cho ứng dụng của mình. Này
| các tuyến đường được tải bởi RouteServiceProvider trong một nhóm mà
| chứa nhóm phần mềm trung gian "web". Bây giờ tạo ra một cái gì đó tuyệt vời!
|
*/ 

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', function() {
    return redirect('stocks');

});

Route::resource('stocks', StockController::class);

product_Management/app/Stock.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    //use HasFactory;
    public $fillable = [
        'product_name',
        'product_desc',
        'product_qty',
        'product_image',
    ];
}

product_Management/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

product_Management/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

product_Management/app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use App\Stock;

use Illuminate\Http\Request;

class StockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stocks = Stock::latest()->paginate(5);
        return view('stocks.index',compact('stocks'))->with('i', (request()->input('page',1) -1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('stocks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'product_name' => 'required',
            'product_desc' => 'required',
            'product_qty' => 'required',
            'product_image' => 'required'
        ]);

        Stock::create($request->all());
        return redirect()->route('stocks.index')->with('success','Created Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Stock $stock)
    {
        //
        return view('stocks.show',compact('stock'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Stock $stock)
    {
        //
        return view('stocks.edit',compact('stock'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Stock $stock)
    {
        //
        $request->validate([
            'prduct_name' => 'required',
            'prduct_desc' => 'required',
            'prduct_qty' => 'required',
        ]);

        $stock->update($request->all());
        return redirect()->route('stocks.index')->with('success','Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Stock $stock)
    {
        //
        $stock->delete();
        return redirect()->route('stocks.index')->with('success','Student deleted successfully.');
    }
}

product_Management/resources/views/stocks/create.blade.php
@extends('stocks.layout')
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Add Stock</h2>
        </div>

        <div class="col-lg-12 text-center" style="margi-top:10px; margin-bottom: 10px;">
            <a class="btn btn-primary" href="{{ route('stocks.index') }}"> Back</a>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Oops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>

                @endforeach
            </ul>
        </div>

    @endif
    <form action="{{ route('stocks.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>
                        Product Name:</strong>
                    <input type="text" name="product_name" class="form-control" placeholder="Product Name">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>
                        Product Description:</strong>
                    <textarea class="form-control" style="height: 150px" name="product_desc"
                        placeholder="Product Description"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Qty:</strong>
                    <input type="numbe" name="product_qty" class="form-control" placeholder="Quantity">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>
                        Image</strong>
                    <input type="text" name="product_image" class="form-control" placeholder="Image">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>

@endsection

product_Management/resources/views/stocks/edit.blade.php
@extends('stocks.layout')
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Edit Stock</h2>
        </div>
        <div class="col-lg-12 text-center" style="margin-top:10px; margin-bottom: 10px;">
            <a class="btn btn-primary" href="{{ route('stocks.index') }}"> Back</a>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Error!</strong>Check your input data<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>

                @endforeach
            </ul>
        </div>

    @endif

    <form action="{{ route('stocks.update', $stock->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Product Name:</strong>
                    <input type="text" name="product_name" value="{{ $stock->product_name }}" class="form-control"
                        placeholder="Product Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>
                        Product Description:</strong>
                    <textarea class="form-control" name="product_desc" style="height: 150px"
                        placeholder="Product Description">{{ $stock->product_desc }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Qty:</strong>
                    <input type="number" name="product_qty" value="{{ $stock->product_qty }}" class="form-control"
                        placeholder="Quantity">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>
                        Image</strong>
                    <input type="text" name="product_image" value="{{ $stock->image }}" class="form-control"
                        placeholder="Image">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>


@endsection

product_Management/resources/views/stocks/index.blade.php
@extends('stocks.layout')
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Product management</h2>
        </div>

        <div class="col-lg-12 text-center" style="margin-top: 10px; margin-bottom: 10px;">
            <a class="btn btn-success " href="{{ route('stocks.create') }}">Add Stock </a>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}


    @endif

    @if (sizeof($stocks) > 0)

        <table class="table table-bordered">
            <tr>
                <th>
                    No
                </th>
                <th>Product Name</th>
                <th>Product Description</th>
                <th>Qty.</th>
                <th>Image</th>
                <th with="280px">More</th>
            </tr>

            @foreach ($stocks as $stock)

                <tr>
                    <td>
                        {{ ++$i }}
                    </td>
                    <td>
                        {{ $stock->product_name }}
                    </td>
                    <td>
                        {{ $stock->product_desc }}
                    </td>
                    <td>
                        {{ $stock->product_qty }}
                    </td>
                    <td>
                        {{ $stock->product_image }}
                    </td>

                    <td>
                        <form action="{{ route('stocks.destroy', $stock->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('stocks.show', $stock->id) }}">Show</a>
                            <a class="btn btn-primary" href="{{ route('stocks.edit', $stock->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>


            @endforeach
        </table>
    @else
        <div class="alert alert-alert">Start Adding to the Database.</div>
    @endif
    {!! $stocks->links() !!}
@endsection

product_Management/resources/views/stocks/layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title> Product Management </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
     integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>
    <div class="container">
        <div class="card" style="margin-top: 20px;">
            <div class="card-body">
                @yield('content')
            </div>
        </div>
    </div>
</body>

product_Management/resources/views/stocks/show.blade.php
@extends('stocks.layout')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Show Stock</h2>
        </div>
        <div class="col-lg-12 text-center" style="margin-top:10px; margin-bottom: 10px;">
            <a class="btn btn-primary" href="{{ route('stocks.index') }}"> Back</a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md">
            <div class="form-group">
                <strong>Product Name : </strong>
                {{ $stock->product_name }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md">
            <div class="form-group">
                <strong>Product Description : </strong>
                {{ $stock->product_desc }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md">
            <div class="form-group">
                <strong>Quantity : </strong>
                {{ $stock->product_qty }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md">
            <div class="form-group">
                <strong>Image : </strong>
                {{ $stock->product_image }}
            </div>
        </div>
    </div>
@endsection